### ISSUE TITLE
Replace Google Analytics with a libre solution (or nothing)

### ISSUE THREAD

**Issue by Calinou** [red-eclipse/site#11]
Upon looking at the source code of the new site, I saw this:

``` HTML
 <script type="text/javascript">
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-45886576-1', 'redeclipse.net');
            ga('require', 'linkid', 'linkid.js');
            ga('send', 'pageview');
</script>
```

It goes without saying that this is a privacy concern -- Google can know when you visit the site.

Please, use something like [Piwik](http://piwik.org) instead, or drop Google Analytics tracking entirely.

(By the way, it would be better if files were served locally instead of using external CDNs.)

**Comment by Croydon** [comment]
:+1: :+1: :+1:

**Comment by shirepirate** [comment]
this was in the old site as well.
in fact, i think it's a tool quin has specifically made use of in the past. i wouldn't recommend dropping it even if that weren't the case though

**Comment by gynter** [comment]
I'm using piwik myself too, is good. :+1:

**Comment by freezurbern** [comment]
I vote against this as GA is a very nice tool that users nowadays can easily opt out of.

**Comment by Calinou** [comment]
> I vote against this as GA is a very nice tool that users nowadays can easily opt out of.

What does GA bring you that Piwik doesn't, for a _non-commercial_ site?

**Comment by ghost** [comment]
Because Piwik is not a 'non-commercial site'. It is a non-commercial _program_.

So here's why GA > Piwik: You have to (a) host Piwik yourself and (b) because Google Analytics is objectively superior in featureset and data presentation and (c) because there is a vast amount of literature on interpreting the results of Google Analytics and next to nothing for Piwik.

**Comment by Croydon** [comment]
It's an advantage to host Piwik yourself. You aren't depend on a third party and you don't give your users data out of control. Also I'm not sure which features the RE team is REALLY using in GA and isn't provided by Piwik.

**Comment by ghost** [comment]
It's an advantage to host it yourself, until you look at its ridiculous memory consumption and resource requirements.

Let me be clear, I actually don't see the point of _any_ analytics library for a single, static page like redeclipse.net. I just don't think Calinou was using the correct rationale or approach or to the matter.

**Comment by qreeves** [comment]
I've been using GA to track download trends and exit points for almost eight years now. It has survived four relocations of the website where piwik didn't. It requires no management on my part, which is especially important.
