### ISSUE TITLE
New reCAPTCHA is broken

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/site#15]
It started with this (4/2/16):

```
[13:47:59] <MeroDN> do you know what?
[13:48:25] <MeroDN> You can't sign up for the forum
[13:48:34] <MeroDN> due to varius bugs
[13:48:51] <MeroDN> the captcha doesn't work
[13:49:10] <MeroDN> the admin email is just some no-reply
[13:49:50] <MeroDN> so im here
[13:50:19] <MeroDN> can anyone who has acces to the forum make a post about the issue?
```

Begin filling out the form, then click submit...
![1](https://cloud.githubusercontent.com/assets/6363417/14228782/db8d4f74-f8ed-11e5-8225-cdd760a2e053.png)
finally gets to this page...
![2](https://cloud.githubusercontent.com/assets/6363417/14228783/db8ed68c-f8ed-11e5-86b9-08ebf2ded8fd.png)
At the top it says:

```
[phpBB Debug] PHP Warning: in file [ROOT]/recaptcha/ReCaptcha/RequestMethod/Post.php on line 68: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: Connection timed out
```

The page is 'crunched' and does not allow the user to try again, not that it helps. This is preventing new users from registering on the forum. 

@qreeves 0223202bf396e2a3ac095c09e34a44f0b7846cbd

**Comment by qreeves** [comment]
I can't pin down why this isn't working, I've reverted to GD image for the captcha for now. Anyone with more experience with PHP(bb) would be welcomed.
