### ISSUE TITLE
SQL error when searching for author in forum

### ISSUE THREAD

**Issue by robalni** [red-eclipse/site#17]
I go to the forum and click "View your posts" near the top of the page. This takes me to https://redeclipse.net/forum/search.php?search_id=egosearch where I see this error message:

> General Error
> 
> SQL ERROR [ mysqli ]
> 
> Expression #​1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'redeclipse.p.post_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [1055]

When I go to https://redeclipse.net/forum/search.php and search for author (by typing an existing user name there), it gives me this: 

> General Error
>
> SQL ERROR [ mysqli ]
> 
> Expression #​1 of ORDER BY clause is not in SELECT list, references column 'redeclipse.p.post_time' which is not in SELECT list; this is incompatible with DISTINCT [3065]

**Comment by acerspyro** [comment]
Forum is b0rk, but we intend to replace it with something more modern. There is no reason to waste time on such an old forum engine. (hint: It's finally gonna get a Red Eclipse theme!)

**Comment by TheAssassin** [comment]
There's definitely something broken, I think we should attempt to find the root cause. @acerspyro otherwise a migration will likely fail.

**Comment by acerspyro** [comment]
The root cause is probably that someone tried to apply an update to PhpBB
and it failed, and no one ever fixed it. @TheAssassin

**Comment by qreeves** [comment]
It started after icculus.org was restored from a backup on an upgraded system and likely due to a difference in software versions somewhere along the line.

**Comment by TheAssassin** [comment]
@qreeves I assume you didn't make backups of the database back then yourself?
