### ISSUE TITLE
Better page template

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/site#2]
Currently, the style of the Red Eclipse homepage is very fixed with a lot of wasted vertical space at the top. Two things would be desired to accomplish:
- Move the main content up in general, perhaps placing the logo smaller elsewhere on the page.
- Make the template itself more generic so other pages can be generated for it (eg. A page for listing downloads, etc).

Requires modification of the main site PHP and CSS.

**Comment by gynter** [comment]
My recommendation is to rewrite the whole template on top of [Bootstrap](http://getbootstrap.com/), this also gives possibility to add support for mobile devices. Also way easier to manage grid design and create generic content pages without messing up the design.
- I'd move the menu to the top (similar to [this template](http://www.templategarden.com/preview/nova/));
- After menu I'd put the main content/point of interest part (description, download link, video, and screnshots);
- Then the powered by, IndieDB and after that other content;
- I'd also make the center a bit of wider, this gives possibility to increase text size and bring out points of interest more (eg the main features and OS support part).

If You decide to go with those changes, I'd be happy to help. If not, I'd still be happy to help :)

**Comment by qreeves** [comment]
@gynter That's what pull requests are for! :stuck_out_tongue: If you come up with something better than what we have we'll probably use it. I've been wanting to make the site "responsive" for a while now, but I'm not a web developer nor do we really have one on hand to do this stuff :disappointed:

**Comment by Calinou** [comment]
[Bootswatch](https://bootswatch.com/) provides free/libre themes for Bootstrap.
