### ISSUE TITLE
Add a responsive favicon

### ISSUE THREAD

**Issue by Calinou** [red-eclipse/site#3]
Using http://realfavicongenerator.net/, you can generate a responsive favicon for the site. The recommended source image size is 260² pixels.

**Comment by qreeves** [comment]
You wanna generate it using the 512² emblem with the transparent background, do the other things it complains about, and submit a pull request for me? :stuck_out_tongue:

**Comment by freezurbern** [comment]
Can this be closed with PR #4 ?
