### ISSUE TITLE
Upgrade to more recent jQuery

### ISSUE THREAD

**Issue by Calinou** [red-eclipse/site#5]
We should probably be using a more recent, supported jQuery version.

2.0 drops support for IE 6/7/8, but 1.9 supports even IE 6.

Right now, we are using a version from 2009:

```
jQuery JavaScript Library v1.3.2
```

We could also use a minified version for faster page loading.

**Comment by freezurbern** [comment]
Upgrading to [2.1.3](http://code.jquery.com/jquery-2.1.3.min.js) Works okay, except a small error in the lightbox code. Perhaps the lightbox should be upgraded at the same time? It is from 2008, and I couldn't find a newer version from the same author.

**Comment by Croydon** [comment]
The minified version should always be getting used in productive environments. Saves file size, disadvantages none.

**Comment by ghost** [comment]
There's a lot of lightbox scripts for jQuery.

Some popular examples in no particular order:
- [Fluidbox](http://terrymun.github.io/Fluidbox/) (very slick, like Medium)
- [Lightbox 2](http://lokeshdhakar.com/projects/lightbox2/) (bit heavy, IMO)
- [Magnific Popup](http://dimsemenov.com/plugins/magnific-popup/) (quite lightweight and works with Zepto)
- [VenoBox](http://lab.veno.it/venobox/) (preserves height)

**Comment by gynter** [comment]
Could and should be done with #2. Not only minified version increase loading time, but also putting JavaScript at the end. Concating all JS into one file is also a good idea, reduces DNS lookups.

**Comment by RemiClouet** [comment]
Bootstrap use 1.11.2. Now use min version and all scrpit at the end. Still need to find a compatible lightbox though.
Edit: fixed. now use 1.11.2, min version at the end of body, and working lightbox

**Comment by Calinou** [comment]
I've been able to use jQuery 2.x with Bootstrap. Are there any incompatibilies, other than the lack of IE8 support?

**Comment by RemiClouet** [comment]
I don't think so, but maybe with the lightbox plugin, idk.
